version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "naslundx"
      - "vonNiklasson"
      - "redfungus"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "naslundx"
      - "vonNiklasson"
      - "redfungus"
