name: Publish

on:
  push:
    branches:
      - 'releases/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools and wheel first
      run: pip3 install setuptools wheel

    - name: Install dependencies (Python)
      run: make update

    - name: Build package
      run: make build

    - name: Test publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_test_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}

    - name: Fetch package version
      run: echo "PACKAGE_VERSION=$(make version)" >> $GITHUB_ENV

    - name: Build docs
      run: make docs

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: docs/_build/html

    - name: Notify Slack channel
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        method: 'POST'
        data: '{"version": "${{ env.PACKAGE_VERSION }}"}'
